# prometheus.yml
global:
  scrape_interval: 15s  # Default scrape interval

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [icmp]  # Use 'http_2xx' for HTTP check, 'icmp' for ping
    static_configs:
      - targets:
          - "8.8.8.8"       # Replace with the IP you want to monitor
          - "1.1.1.1"
          - "100.1.1.1"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance  # This will label the IP address
      - target_label: __address__
        replacement: blackbox-exporter:9115  # Blackbox Exporter address
